# Generated by Django 5.1.2 on 2024-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_feedback_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
