# Generated by Django 5.1.2 on 2024-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_feedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
