# Generated by Django 5.1.2 on 2024-12-13 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_feedback_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='days_booked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
